/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorVentanaTarifas;
import Modelos.Tarifas;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 */
public class VistaTarifas extends javax.swing.JFrame {

    ControladorVentanaTarifas controlador;
    
    /**
     * Creates new form VistaTarifas
     */
    
    public VistaTarifas() {
        initComponents();
        this.controlador = new ControladorVentanaTarifas();
        Tarifas tarifaCarro = controlador.obtenerTarifaCarro();
        Tarifas tarifaHibrido = controlador.obtenerTarifaHibrida();
        Tarifas tarifaClasico = controlador.obtenerTarifaClasica();
        txtActuClas.setText(tarifaClasico.getValor());
        txtActuHibrida.setText(tarifaHibrido.getValor());
        txtActuCarro.setText(tarifaCarro.getValor());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtActuHibrida = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtActuClas = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        nuevoHibrida = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        nuevoClasica = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtActuCarro = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        nuevoCarro = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Clásica");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tarifas para vehículos por hora");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Motos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Híbrida");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Ingrese el nuevo valor:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        txtActuHibrida.setEditable(false);
        txtActuHibrida.setBackground(new java.awt.Color(255, 255, 255));
        txtActuHibrida.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtActuHibrida.setForeground(new java.awt.Color(0, 0, 153));
        txtActuHibrida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtActuHibrida.setBorder(null);
        jPanel1.add(txtActuHibrida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 130, 10));

        txtActuClas.setEditable(false);
        txtActuClas.setBackground(new java.awt.Color(255, 255, 255));
        txtActuClas.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtActuClas.setForeground(new java.awt.Color(0, 0, 153));
        txtActuClas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtActuClas.setBorder(null);
        jPanel1.add(txtActuClas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 130, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, 10));

        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Ingrese el nuevo valor:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 30));

        nuevoHibrida.setBackground(new java.awt.Color(255, 255, 255));
        nuevoHibrida.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        nuevoHibrida.setForeground(new java.awt.Color(0, 0, 153));
        nuevoHibrida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoHibrida.setBorder(null);
        jPanel1.add(nuevoHibrida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, 10));

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Guardar");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 80, 20));

        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("Valor actual:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 20));

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Guardar");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        nuevoClasica.setBackground(new java.awt.Color(255, 255, 255));
        nuevoClasica.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        nuevoClasica.setForeground(new java.awt.Color(0, 0, 153));
        nuevoClasica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoClasica.setBorder(null);
        jPanel1.add(nuevoClasica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 130, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 10));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Carros");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtActuCarro.setEditable(false);
        txtActuCarro.setBackground(new java.awt.Color(255, 255, 255));
        txtActuCarro.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        txtActuCarro.setForeground(new java.awt.Color(0, 0, 153));
        txtActuCarro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtActuCarro.setBorder(null);
        jPanel1.add(txtActuCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 130, 10));

        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Ingrese el nuevo valor:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 130, 30));

        nuevoCarro.setBackground(new java.awt.Color(255, 255, 255));
        nuevoCarro.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        nuevoCarro.setForeground(new java.awt.Color(0, 0, 153));
        nuevoCarro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nuevoCarro.setBorder(null);
        jPanel1.add(nuevoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 130, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 130, 10));

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Guardar");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 80, 20));

        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Valor actual:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 90, 20));

        jPanel6.setBackground(new java.awt.Color(0, 0, 153));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Volver");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("Valor actual:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if(txtActuHibrida.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nuevo valor para la moto híbrida");   
        }else {
            String valor = nuevoHibrida.getText();
            controlador.actualizarTarifaHibrida(valor);
            JOptionPane.showMessageDialog(null, "Se actualizo correctamente");
            Tarifas tarifaHibrido = controlador.obtenerTarifaHibrida();
            txtActuHibrida.setText(tarifaHibrido.getValor());
            limpiarCampos();
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(txtActuClas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nuevo valor para la moto clásica");   
        }else {
            String valor = nuevoClasica.getText();
            controlador.actualizarTarifaClasica(valor);
            JOptionPane.showMessageDialog(null, "Se actualizo correctamente");
            Tarifas tarifaClasica = controlador.obtenerTarifaClasica();
            txtActuClas.setText(tarifaClasica.getValor());
            limpiarCampos();
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        if(txtActuCarro.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nuevo valor para el carro");   
        }else {
            String valor = nuevoCarro.getText();
            controlador.actualizarTarifaCarro(valor);
            JOptionPane.showMessageDialog(null, "Se actualizo correctamente");
            Tarifas tarifaCarro = controlador.obtenerTarifaCarro();
            txtActuCarro.setText(tarifaCarro.getValor());
            limpiarCampos();
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.dispose();
        JFrame v2 = new VistaPrincipal();
        v2.setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    public void limpiarCampos(){
        nuevoCarro.setText(null);
        nuevoClasica.setText(null);
        nuevoHibrida.setText(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nuevoCarro;
    private javax.swing.JTextField nuevoClasica;
    private javax.swing.JTextField nuevoHibrida;
    private javax.swing.JTextField txtActuCarro;
    private javax.swing.JTextField txtActuClas;
    private javax.swing.JTextField txtActuHibrida;
    // End of variables declaration//GEN-END:variables
}
